Update CI.yml

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -47,14 +47,13 @@ jobs:
     - name: VSTest
       run: vstest.console LernsituationOOPTests\bin\Release\LernsituationOOPTests.dll
       
-    - name: Upload coverage
-      if: success()
-      run: |
-        curl -s https://codecov.io/bash | bash
-      env:
-        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
-        CODECOV_NAME: ${{ runner.os }} Python ${{ matrix.python-version }}
-      shell: bash
+    - name: Upload coverage to Codecov
+      env: 
+        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
+      run: |-
+        curl -s https://codecov.io/bash | bash -s -- \
+        -F "unittests" \
+        -Z || echo 'Codecov upload failed'
         
     - name: Upload Artifact
       uses: actions/upload-artifact@v1.0.0
